@serve:
  ../maelstrom/maelstrom serve

# Stage 1

@stage-1-test:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --log-stderr \
    --log-net-recv \
    --log-net-send \
    --node-count 1 \
    --time-limit 1 \
    --rate 10

@stage-1-validate:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --node-count 1 \
    --time-limit 20 \
    --rate 10

# Stage 2

@stage-2-test:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --log-stderr \
    --log-net-recv \
    --log-net-send \
    --node-count 2 \
    --time-limit 1 \
    --rate 10

@stage-2-validate:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --node-count 5 \
    --time-limit 20 \
    --rate 10

# Stage 3

@stage-3-test:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --log-stderr \
    --log-net-recv \
    --log-net-send \
    --node-count 2 \
    --time-limit 1 \
    --rate 10 \
    --nemesis partition

@stage-3-validate:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --node-count 5 \
    --time-limit 20 \
    --rate 10 \
    --nemesis partition

# Stage 4

@stage-4-test:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --log-stderr \
    --log-net-recv \
    --log-net-send \
    --node-count 2 \
    --time-limit 1 \
    --rate 100 \
    --latency 100

@stage-4-test-partition:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --log-stderr \
    --log-net-recv \
    --log-net-send \
    --node-count 2 \
    --time-limit 1 \
    --rate 100 \
    --latency 100 \
    --nemesis partition

@stage-4-validate:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --node-count 25 \
    --time-limit 20 \
    --rate 100 \
    --latency 100

@stage-4-validate-partition:
  ../maelstrom/maelstrom test \
    --workload broadcast \
    --bin main.py \
    --node-count 25 \
    --time-limit 20 \
    --rate 100 \
    --latency 100 \
    --nemesis partition
